{% set name = "nestml" %}
{% set version = "7.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nest/nestml/archive/v{{ version }}.tar.gz
  sha256: d2cc7b119b2b2eda98ac1b148d4e947f77fef2fdce563ff829b7d7185ce81be3

build:
  noarch: python
  number: 0
  entry_points:
    - nestml = pynestml.frontend.pynestml_frontend:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3 
    - pip
  run:
    - python >=3 
    - numpy >=1.8.2
    - sympy
    - scipy
    - antlr4-python3-runtime ==4.13
    - setuptools
    - jinja2 >=2.10
    - typing 
    - astropy
    - odetoolbox >=2.4
    - ipython 
    - cxx-compiler 
    - pyqt 
    - wxpython 
    - libboost-python-devel 
    - libboost-devel 
    - cmake 
    - make

test:
  imports:
    - pynestml
  commands:
    - nestml --help
  requires:
    - pip

about:
  home: https://github.com/nest/nestml
  summary: 'NESTML: The NEST Modelling Language'
  description: |
    NESTML is a domain-specific language that supports the specification 
    of neuron models in a precise and concise syntax, based on the syntax 
    of Python. Model equations can either be given as a simple string of 
    mathematical notation or as an algorithm written in the built-in 
    procedural language. The equations are analyzed by the associated 
    toolchain, written in Python, to compute an exact solution if possible 
    or use an appropriate numeric solver otherwise.
  license: GPL-2.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - steffengraber
