github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
azure:
    force: False
    store_build_artifacts: true
    free_disk_space: False
    max_parallel: 25
